name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: yarn install, yarn lint, yarn build
      run: |
        yarn install
        yarn build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.
        # CNAME: crypt32dll.github.io
