name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: yarn install, yarn lint, yarn build
      run: |
        yarn install
        yarn build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
        CNAME: crypt32dll.github.io
    - name: generate-sitemap
      # You may pin to the exact commit or the version.
      uses: cicirello/generate-sitemap@v1.5.0
      with:
        # The path to the root of the website
        path-to-root: /
        # The url of your webpage
        base-url-path: https://crypt32dll.github.io
